apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
  namespace: portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: kanghyeonseung/portfolio-service
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: portfolio-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: portfolio-service
spec:
  selector:
    app: portfolio-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP